### ISSUE TITLE
Editing of batch labels impossible

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#691] opened 2018-02-23 16:14 UTC
## Steps to reproduce
- Go to setup/batch labels
- click on an existing batch label

## Current behavior
At senaite.ridingbytes.com error message:

`<zope.traversing.namespace.view object at 0x7f4c62493a10>
`

At our own testmachine: Insufficient Privileges (even as admin)

## Expected behavior
Editing batch label

**Comment by ramonski** [comment] 2018-02-23 16:32
Looks like a duplicate of https://github.com/senaite/senaite.core/issues/590

**Comment by xispa** [comment] 2018-03-08 11:41
Indeed. a duplicated of #590 . Closing

**Closed by xispa** 2018-03-08 11:41 UTC

**Comment by grulisco** [comment] 2018-05-25 15:18
@xispa or @juangallostra: Please reopen issue, as it is again a problem after latest update of our test instance by @ramonski.
