### ISSUE TITLE
Error: Labclerks viewing verified worksheets

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#1396] opened 2019-06-18 14:23 UTC
## Description

Labclerks cannot view worksheets in verified status.

## Reproduction guide

- Login with labclerk privileges
- Goto Worksheet view
- select one of the verified worksheets

## Observed behaviour
Browser Error: ERR_TOO_MANY_REDIRECTS

## Expected behaviour

View verified worksheet

## Versions

- OS: Linux

- senaite.core: `master`
- senaite.impress: `master`
- senaite.core.listing: `master`
- senaite.core.supermodel: `master`

**Comment by grulisco** [comment] 2019-11-28 21:09
@xispa @ramonski: On our updated testmachine labclerks can access verified worksheets now, but they are empty. samples and analyses are not displayed yet. Please reopen issue.

**Comment by grulisco** [comment] 2020-03-05 22:52
still a problem after upgrade to core 1.3.3

**Comment by ramonski** [comment] 2020-03-06 09:41
The problem was found in the add-on and not in `senaite.core`. Closing.

**Closed by ramonski** 2020-03-06 09:41 UTC
Labels: Bug, Issue done, P1: Urgent

**Comment by ramonski** [comment] 2020-03-06 09:56
@grulisco please test on your system and confirm that the problem is resolved.
The problem was the same as resolved here: https://github.com/senaite/senaite.core/pull/1479 but in the domain of the add-on.

**Comment by grulisco** [comment] 2020-03-06 14:00
@confirmed for test instance.

**Comment by grulisco** [comment] 2020-03-07 10:06
@ramonski confirmed for productive instance :smile:
