### ISSUE TITLE
ImportError: cannot import name _remove_dead_weakref

### ISSUE THREAD

**Issue by iranpak** [senaite/senaite.core#1619] opened 2020-09-21 18:47 UTC
## Description

Hi. 
while installing plone with `./install.sh standalone --target=/home/senaite --instance=senaitelims --password=admin` i get following error. i followed installtion guide exactly on this link: [https://www.senaite.com/docs/installation](url)!

`Traceback (most recent call last):
  File "/home/senaite/tmp/helper_scripts/create_instance.py", line 9, in <module>
    import argparse
  File "/home/senaite/miniconda2/envs/senaite/lib/python2.7/argparse.py", line 86, in <module>
    import copy as _copy
  File "/home/senaite/miniconda2/envs/senaite/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/home/senaite/miniconda2/envs/senaite/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
`

what should i do?

**Comment by xispa** [comment] 2020-09-23 19:03
This might help: https://stackoverflow.com/questions/55515144/importerror-cannot-import-name-remove-dead-weakref-in-django-virtualenv#answer-56140705

**Comment by ramonski** [comment] 2020-09-29 21:14
Closing this issue, because there is no communication back and clearly an installation issue and not a bug in the code.

**Closed as completed by ramonski** 2020-09-29 21:14 UTC
