### ISSUE TITLE
Categorise analysis services is not working for "View" and "Manage Results"

### ISSUE THREAD

**Issue by siyamalan** [senaite/senaite.core#1400] opened 2019-06-25 12:29 UTC
## Description

When there is a large number of analysis, categorise option makes it easier to view/enter data

For a company,  exporting a product to several countries, combination of calculator and categorise option can be used to enter fewer data and but display out of spec results for all markets.
![image](https://user-images.githubusercontent.com/20146320/60097745-230f0e80-97a8-11e9-9c00-ce04398bf2c6.png)

## Observed behaviour
I chose categorise option. it is working for "Manage Analyses" tab and in printed reports.
Not working for "view" and "manage results"
 
![image](https://user-images.githubusercontent.com/20146320/60097955-9f095680-97a8-11e9-9433-f815488bea10.png)

 Not working in 
https://github.com/senaite/senaite.core/blob/master/bika/lims/browser/analysisrequest/view.py
https://github.com/senaite/senaite.core/blob/master/bika/lims/browser/analysisrequest/manage_results.py

Working in 
https://github.com/senaite/senaite.core/blob/master/bika/lims/browser/analysisrequest/manage_analyses.py

This **categorise option** is working properly for all three in Previous senaite core 1.2.9 version. Looks like it has been removed in senaite core 1.3.1

## Versions

- OS: Linux

- senaite.core: `master`
- senaite.impress: `master`
- senaite.core.listing: `master`
- senaite.core.supermodel: `master`

## Traceback
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by xispa** [comment] 2019-11-26 17:42
Duplicate of #1323

**Closed by xispa** 2019-11-26 17:42 UTC
Labels: Enhancement
