### ISSUE TITLE
Cannot add attachments to a worksheet when auto-import of results is used

### ISSUE THREAD

**Issue by Lunga001** [senaite/senaite.core#595] opened 2018-01-22 18:34 UTC
## Steps to reproduce
     1. Add instrument
          
![abbott m2000 real time senaite](https://user-images.githubusercontent.com/10023210/35235803-d94bd596-ffad-11e7-85d1-0ea663fc1cce.png)
    2. Create a  folder  named instruments/abbott(at the root of your project or under zeoscluster folder if 
        using a zeoserver)where  the system should look for the results files while automatically importing 
        results
    3. Copy the file from bikalims/lims/tests/files/Results.log.123 to the created folder in number 2
    4. Create an AR that has the analyses that are on Results.log.123 or you can change the analyses 
         that are there to match the one you have just created on the AR(change HIV0.6ml to Ca for 
         example). Also change H2O-0001 to the AR number
    5. Create a Worksheet and make sure that the  AR on the Results.log.123 are on the worksheet
    6. Go Bika Setup --> Sampling and coc --> Change Interval of Auto-Importing Files in minutes to 10
    7. Run http://localhost:8081/senaite/auto_import_results
    8. Go to the instrument you have created and click on Auto Import Logs, on the Results column there 
        should be a traceback message
    To view the full traceback message go to instruments/abbott and read the logs.log file   

## Current behavior  
    I'm getting an this error.
    File "/home/lunga/instances/senaite-ace-
    zeo/zeocluster/src/senaite.core/bika/lims/browser/resultsimport/resultsimport.py", line 110, in __call__
    importer.process()
    File "/home/lunga/instances/senaite-ace-
    zeo/zeocluster/src/senaite.core/bika/lims/exportimport/instruments/resultsimport.py", line 485, in 
    process
    self.create_attachment(ws, infile)
    File "/home/lunga/instances/senaite-ace-
    zeo/zeocluster/src/senaite.core/bika/lims/exportimport/instruments/resultsimport.py", line 570, in 
    create_attachment
    AttachmentKeys='Results, Automatic import')
    File "/home/lunga/instances/senaite-ace-zeo/buildout-cache/eggs/Products.Archetypes-1.9.17-
    py2.7.egg/Products/Archetypes/BaseObject.py", line 428, in update
    self.Schema().updateAll(self, **kwargs)
    File "/home/lunga/instances/senaite-ace-zeo/buildout-cache/eggs/Products.Archetypes-1.9.17-
    py2.7.egg/Products/Archetypes/Schema/__init__.py", line 528, in updateAll
    method(kwargs[name])
    File "/home/lunga/instances/senaite-ace-zeo/buildout-cache/eggs/Products.Archetypes-1.9.17-
    py2.7.egg/Products/Archetypes/ClassGen.py", line 76, in generatedMutator
    return schema[name].set(self, value, **kw)
    File "/home/lunga/instances/senaite-ace-zeo/buildout-cache/eggs/plone.app.blob-1.5.19-
    py2.7.egg/plone/app/blob/field.py", line 247, in set
    blobbable = IBlobbable(value)
   TypeError: ('Could not adapt', <bika.lims.browser.resultsimport.resultsimport.ConvertToUploadFile 
   instance at 0x7f4c46808a70>, <InterfaceClass plone.app.blob.interfaces.IBlobbable>)

   This happens when I run auto_import_results (http://localhost:8081/senaite/auto_import_results).
    It happens when trying to update the results of the analyses that are attached to a worksheet. 

## Expected behavior
      The log file should have something similar to "Import finished successfully: 1 ARs, 0 Instruments and 
      1 results updated"

**Comment by xispa** [comment] 2018-07-18 09:04
@Lunga001 is this issue a duplicate of https://github.com/senaite/senaite.core/issues/852? If so, I guess we can close this one right?

**Comment by Lunga001** [comment] 2018-07-18 09:16
Yep

**Closed** 2018-07-18 09:16 UTC
Labels: Bug, P3: Important
