### ISSUE TITLE
UI - tabs

### ISSUE THREAD

**Issue by jasmina-stgn** [senaite/senaite.core#1670] opened 2020-10-21 15:57 UTC
## Description

First tab is always selected on some screens regardless of what screen you are on, see screenshots for reference.
@@usergroup-userprefs 
@@personal-information

## Reproduction guide

<<REPRODUCTION STEPS>>

## Observed behaviour
First tab always selected.

## Expected behaviour
Correct tab should be selected.

## Versions

- OS: Linux Ubuntu 18

- senaite.core: `master`
- senaite.impress: `master`
- senaite.core.listing: `master`
- senaite.core.supermodel: `master`

Senaite core and LIMS 1.3.4

## Traceback
```
<<BACKTRACE IF RELEVANT>>
```
## Screenshot
![image](https://user-images.githubusercontent.com/73239116/96732467-448a0580-13b0-11eb-8d3a-da74d9a954e7.png)
![image](https://user-images.githubusercontent.com/73239116/96732694-8915a100-13b0-11eb-9ca0-ac14f772e98b.png)

**Comment by rockfruit** [comment] 2021-07-26 12:48
I can't reproduce this.  In my environment, which was first configured about a week ago, all tabs on all screens in site setup as well as frontend, work perfectly.

If this persists with the latest version of things, then I suppose you'd be better off asking Plone guys what could be wrong there, or how to debug it.

**Comment by ramonski** [comment] 2021-12-08 15:05
Closing due to no further response

**Closed as completed by ramonski** 2021-12-08 15:05 UTC
