### ISSUE TITLE
A user with "Analyst" role is not able to submit the "analysis" from worksheet

### ISSUE THREAD

**Issue by pioneerpathan** [senaite/senaite.core#1409] opened 2019-07-05 06:29 UTC
## Description

A user with role/group "Analyst" is able to save the result for assigned analysis but after saving the result he is not able to submit the analysis for further step (for verification).

## Reproduction guide

1. Create a user with role/group "Analyst"

2. Login with a user with role/group "Client" and create a new Analysis Request

3. Now login with a user with role/group "Labmanager" and receive the Analysis Request just created by the client.

4. After receiving the Analysis Request, go to "worksheet" tab, select analyst name, which we had just created with role "Analyst" and click on "Add" button to create a new worksheet.

5. Assign the analysis requested by client in a new Analysis Request to selected "Analyst".

6. Now login with a user with role "Analyst", open assigned worksheet, enter the result for assigned analysis and click on "Save" button.

7. Analysis result will get saved. But now "Analyst" can not submit it for further step of verification. 

## Observed behaviour

It seems, "Analyst" can only save the analysis result but he can not submit it for further verification through worksheet. 

"Submit" button is visible in "Labmanager" login.

## Expected behaviour

"Analyst" should be able to submit the analysis in worksheet for verification.

## Versions

- OS: Linux - Fedora 27

- senaite.core: `master` - v 1.3.2
- senaite.impress: `master`- v 1.2..1
- senaite.core.listing: `master` - 1.2.0
- senaite.core.supermodel: `master`

## Traceback
```
<<BACKTRACE IF RELEVANT>>
```

## Screenshot
![image](https://user-images.githubusercontent.com/9590337/60701876-d6030900-9f1a-11e9-8eea-1c8dddb6e032.png)

![image](https://user-images.githubusercontent.com/9590337/60702115-8d981b00-9f1b-11e9-9038-5ccd92b6909f.png)

**Comment by xispa** [comment] 2019-07-05 14:48
Hi @pioneerpathan , I've tried to reproduce this issue without success.

The following is the code of the submit guard:

https://github.com/senaite/senaite.core/blob/037c104eef77bd17ea24e1b319c1ee33725ac899/bika/lims/workflow/analysis/guards.py#L104-L145

So, some questions:

1. Is the point of capture of the analysis set to "Lab" or "Field"?
2. Is the option "Allow analysts other than assigned to submit" from Setup disabled or enabled?
3. Is the analysis dependent on other analyses because of a calculation?
4. Does the analysis have the option "require attachment" enabled?

**Comment by pioneerpathan** [comment] 2019-07-05 15:52
Hi jordi,

This is pioneerpathan. I am out of station. Reply to your questions on
Monday.

Answer from on the go memory as below.

1. Analysis - point of capture is "lab"
2. I have disabled this option. Only assigned analyst can submit results.
3. There is nocalculationv dependency
4. I haven't touch attachment option. So whatever is default will be there.

**Comment by pioneerpathan** [comment] 2019-07-09 04:46
Hi Jordi,

Sorry for the delay. I am now back in office. And please find following answers in-line to your queries with cross-checking in the system:

1. Is the point of capture of the analysis set to "Lab" or "Field"? **Lab**
2. Is the option "Allow analysts other than assigned to submit" from Setup disabled or enabled? **disabled**

![image](https://user-images.githubusercontent.com/9590337/60859940-fd671800-a231-11e9-8005-9731c06572c6.png)

3. Is the analysis dependent on other analyses because of a calculation? **No calculation specified, hence no dependency**

![image](https://user-images.githubusercontent.com/9590337/60860005-4a4aee80-a232-11e9-87d6-b2a5bf60be4c.png)
 
4. Does the analysis have the option "require attachment" enabled? **It is Permitted**

**Comment by pioneerpathan** [comment] 2019-07-09 05:07
Hi Jordi,

I have also checked submit guard code. There is no difference in code.

**Comment by pioneerpathan** [comment] 2019-07-09 05:35
Hi Jordi,

On my continuous trail and make I found a weird observation. With intention to check in which "IF" condition does submit guard get executed, I inserted some loggers in all "IF" conditions and ran Client1 in "fg" mode. And more was nothing like issue now. I feel it strange. And also nothing logged in console.

I again stop the Client1 instance and now ran it with normal mode without "fg". It seems like there is no issue at all.

As you can see in screen-shots which I uploaded in issue post that I had genuinely faced the issue. I had build the code and restarted the "plonectl" as well. There were no error in build and restart process.

But today after running "client1" in "fg" mode, issue is now disappear. The only thing that I remark between this co-incidence is "System Restart". As I mentioned, when I back to office today, first work I did is power-on the machine as replied to your queries.  

Can you throw some light on the incidence that what has happened ?

**Comment by pioneerpathan** [comment] 2019-07-09 11:14
I found the reason for weird behavior reported in previous comment.

If I say in one line then it is - "It is necessary to create a **_Lab Contact_** for the user with "Analyst" role and link the lab contact with the user"

My mistakes :

1. I created a user with "Analyst" role but didn't created a "Lab Contact" and linking of "Analyst" user with the "Lab Contact". It fails in guard submit code of analyses. Following is the code highlight from file :- senaite.core/bika/lims/workflow/analysis/guards.py

![image](https://user-images.githubusercontent.com/9590337/60883623-49cd4a80-a268-11e9-914a-673387d170d9.png)

**Comment by pioneerpathan** [comment] 2019-07-09 12:14
Problem, still persists.

Creating a "Lab Contact" for an "Analyst" does not work. `analysis.getAnalyst()` is giving empty value hence it is not allowing to submit result to Analyst for verification.

Login with "Analyst" and entering result saves analysis data, but, may be, Who had entered the result data is not being stored. That is why `analysis.getAnalyst` returns empty value.

**Comment by xispa** [comment] 2019-07-09 21:59
If these analyses are in a worksheet, then `analysis.getAnalyst` should not return an empty value. The expected behavior is that when analyses are added into a worksheet, the system should automatically assign same analyst to all them, but this is not happening. Will review the code and report back.

Meanwhile,  can you try to reassign the worksheet to another analyst first and reassign to the initial analyst thereafter?

**Comment by pioneerpathan** [comment] 2019-07-10 05:51
> If these analyses are in a worksheet, then `analysis.getAnalyst` should not return an empty value. The expected behavior is that when analyses are added into a worksheet, the system should automatically assign same analyst to all them, but this is not happening. Will review the code and report back.
> 
> Meanwhile, can you try to reassign the worksheet to another analyst first and reassign to the initial analyst thereafter?

Hi Jordi,

I tried as you suggested. It is working fine. First, I reassigned the worksheet to other analyst and it allows new analyst to submit. I again reassigned it to initial analyst and checked and it now allows initial analyst too to submit.

**Comment by xispa** [comment] 2019-07-10 21:38
Thanks for your feedback @pioneerpathan

**Closed** 2019-11-25 17:58 UTC
Labels: Bug, Issue done, P1: Urgent
