### ISSUE TITLE
Client record is not visible to client himself in clients listing screen

### ISSUE THREAD

**Issue by pioneerpathan** [senaite/senaite.core#1412] opened 2019-07-12 06:54 UTC
## Description

When logged-in as a client, user should be able to see his own client record in clients listing table. The record in listing serves as a link which further takes to sub-menus/tabs belonging to client viz. Edit, Contacts, Analysis Reports etc.

## Reproduction guide

1. Login with a client user which is belong to some client in the system.

2. By default, it takes you to ~/clients/client-[CLIENT_NUMBER]/analysisrequests, means to "Samples" tab.

![image](https://user-images.githubusercontent.com/9590337/61106902-21c62d00-a49c-11e9-8c0d-e5b987c01299.png)

3. Now if user click on "clients" link, it does not shows his own client record to user in clients listing screen.

![image](https://user-images.githubusercontent.com/9590337/61107483-a5344e00-a49d-11e9-9afc-29927fa890f3.png)

## Observed behaviour

A user logged-in as a client, is not able to see his own client record in clients listing screen. So, It is not possible to go to sub-menus/tabs like "Contacts", "Orders", "Analysis Profiles" etc. To access these sub-menus/tabs, the user has to log-out and re-login because the user is being redirected to these tabs as by default after login.

## Expected behaviour

A user logged-in as a client should be able see his own client record in clients listing screen. So that at any point of time, he can visit sub-menus/tabs like "Edit", "Contact", "Orders" etc. The record in clients listing is like a connecting bridge for these sub-menus/tabs.

## Versions

- OS: Linux - Fedora 27

- senaite.core: `master` - v1.3.2
- senaite.impress: `master` - v1.2.1
- senaite.core.listing: `master` - v1.2.0
- senaite.core.supermodel: `master` - v1.2.1

## Traceback
```
There is no error in traceback
```

**Comment by xispa** [comment] 2019-07-16 06:41
A client contact belongs to a single client, so I think the better approach would be to not display the `Clients` nav item, but something like "My Client" that would directly redirect to user to it's own client view.

**Comment by pioneerpathan** [comment] 2019-08-05 06:03
Hello @xispa 

Can you please, suggest me the solution to temporarily enable client listing in case of client login? 
I am paused in my personal development cycle due to this issue. I tried to tinker with permission but I couldn't succeed. It will be really appreciated if you can provide me time being solution or some int to address it.

Thanks

**Comment by xispa** [comment] 2019-08-05 09:50
@pioneerpathan look at https://github.com/senaite/senaite.core/issues/1380#issuecomment-495087230

**Comment by pioneerpathan** [comment] 2019-08-05 11:43
> @pioneerpathan look at [#1380 (comment)](https://github.com/senaite/senaite.core/issues/1380#issuecomment-495087230)

Thanks @xispa ; It worked...!!! 

I don't how but it worked as expected. Before reindexing "allowedRolesAndUsers" index in portal_catalog, I first checked the count for "Objects Indexed" and "Distinct Values" hold by the Index and I re-checked it after reindexing but there was no change in any count. I don't where and what this simple click of "Reindex" button did.

Is it that at somewhere reindexing in not happening by code when it needed ?

Thanks for providing work around solution and saving my day.

**Comment by pioneerpathan** [comment] 2019-08-08 12:18
In further to above work-around, I again register some client's and their respective contacts (users). And I tried with these newly registered user and found that problem re-occurred.

So, again I did the trick with above proposed work-around of re-indexing and then everything is working well. 

This is just an observation that I thought to share.

**Comment by xispa** [comment] 2019-08-12 09:23
Thanks @pioneerpathan for your feedback. It means the client don't get reindexed after you add contact.

**Comment by xispa** [comment] 2019-10-16 17:43
Duplicate of https://github.com/senaite/senaite.core/issues/1380

**Closed by xispa** 2019-10-16 17:43 UTC
Labels: Bug
