### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Radd78** [senaite/senaite.core#576] opened 2018-01-16 08:44 UTC
During installation of Bika:
   sudo -u plone_buildout bin/buildout -v
There's a problem with installing WeasyPrint:

## Current behavior
platform linux2 -- Python 2.7.6, pytest-3.3.2, py-1.5.2, pluggy-0.6.0

## Screenshot (optional)
We have no distributions for WeasyPrint that satisfies 'WeasyPrint==0.42'.
Getting distribution for 'WeasyPrint==0.42'.
Running easy_install:
"/usr/local/PloneBika/Python-2.7/bin/python" "-c" "from setuptools.command.easy_install import main; main()" "-mZUNxd" "/usr/local/PloneBika/zeocluster/../buildout-cache/eggs/tmpyf50qB" "-q" "/usr/local/PloneBika/buildout-cache/downloads/dist/WeasyPrint-0.42.tar.gz"
path=/usr/local/PloneBika/buildout-cache/eggs/setuptools-7.0-py2.7.egg

error: Setup script exited with error in WeasyPrint setup command: Invalid environment marker: python_version < "3.0"
An error occurred when trying to install WeasyPrint 0.42. Look above this message for any errors that were output by easy_install.
While:
  Installing client1.
  Getting distribution for 'WeasyPrint==0.42'.
Error: Couldn't install: WeasyPrint 0.42

**Comment by ramonski** [comment] 2018-01-16 08:59
Duplicate of #560.

Please update your version of `setuptools` or use the turn-key ready VM provided at http://senaite.com.

Thanks for understanding that we can not track individual installation problems in this tracker.

**Closed by ramonski** 2018-01-16 08:59 UTC

**Comment by Radd78** [comment] 2018-01-16 14:01
Thank You
